server:
  port: 8090
  servlet:
    context-path: /auth

spring:
  redis:
    port: 6379
    host: 127.0.0.1
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/oauth2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL


mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: com.sqring.auth.web.entities

# 日志级别，会打印sql语句
logging:
  level:
    com.sqring.auth.web.mapper: debug